version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /data/test-change-streams:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    command: mongod --replSet test-change-streams --logpath /data/db/mongodb.log --dbpath /data/db --port 27017

  mongodb-setup:
    image: mongo:latest
    depends_on:
      - mongodb
    networks:
      - app-network
    command: >
      bash -c "
      mongosh --host mongodb:27017 --eval \"rs.initiate()\" &&
      mongosh --host mongodb:27017 --eval \"rs.reconfig({_id: 'test-change-streams', members: [{ _id : 0, host : 'mongodb:27017'}]}, {force: true})\"
      "
  fastapi-app:
    # image: multilanguage_invoice_ocr-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./config:/app/config
      - ./src:/app/src
    ports:
      - "8149:8149"
    networks:
      - app-network
    depends_on:
      - mongodb
      - mongodb-setup

networks:
  app-network:
    driver: bridge