const fieldLabels = {
    name: "Name",
    project_number: "Vorgangs-Nr.",
    kw: "KW",
    customer: "Kunde",
    city: "Stadt",
    description: "Beschreibung",
    land: "Land",
    is_process_done: "Ist der Vorgang erledigt?",
    is_commissioned_work: "Auftragsarbeit",
    is_without_measuring_technology: "Ohne Messtechnik?",
    sign_date: "Datum der Unterschrift",
    has_employee_signature: "Ist die Unterschrift des Mitarbeiters vorhanden?",
    has_customer_signature: "Ist die Unterschrift des Kunden vorhanden?",
    date: "Datum",
    start_time: "Start Uhrzeit",
    end_time: "Ende Uhrzeit",
    break_time: "Pausenzeit",
    is_in_egw: "Stundenzettel im EWG erstellt?",
    currency: "Währung",
    invoice_type: "Zahlungsart",
    amount: "Betrag",
    amount_change: "Betragsänderung",
    fixed_lines: "Fixed lines",
    sku: "Stock Keeping Unit (SKU)",
    lines: "Lines",
    vatitems: "VAT Items",
    amount_each: "Amount / Item",
    percentage: "Percentage",
    amount_shipping: "Shipping Amount",
    quantity: "Quantity",
    vatamount: "VAT Amount",
    amountexvat: "Amount Ex. VAT",
    purchasedate: "Purchase Date",
    purchasetime: "Purchase Time",
    amount_incl_excl_vat_estimated: "Amount Including or Excluding VAT Estimated ?",
    vat_context: "VAT Context",
    paymentmethod: "Payment Method",
    payment_auth_code: "Payment Auth Code",
    payment_card_number: "Payment Card Number",
    payment_card_account_number: "Payment Card Account Number",
    payment_card_bank: "Payment Card Bank",
    payment_card_issuer: "Payment Card Issuer",
    payment_due_date: "Payment Due Date",
    terminal_number: "Terminal Number",
    document_subject: "Document Subject",
    package_number: "Package Number",
    invoice_number: "Invoice Number",
    receipt_number: "Receipt Number",
    shop_number: "Shop Number",
    transaction_number: "Transaction Number",
    transaction_reference: "Transaction Reference",
    order_number: "Order Number",
    table_number: "Table Number",
    table_group: "Table Group",
    server: "Server",
    merchant_name: "Merchant Name",
    merchant_id: "Merchant ID",
    merchant_coc_number: "Merchant CoC Number",
    merchant_vat_number: "Merchant VAT Number",
    merchant_bank_account_number: "Merchant Bank Account Number",
    merchant_bank_account_number_bic: "Merchant Bank Account Number BIC",
    merchant_chain_liability_bank_account_number: "Merchant Chain Liability Bank Account Number",
    merchant_chain_liability_amount: "Merchant Chain Liability Amount",
    merchant_bank_domestic_account_number: "Händlerkontonummer",
    merchant_bank_domestic_bank_code: "Händler Bank-Code",
    merchant_website: "Händlerwebseite",
    merchant_email: "Händler-Email",
    merchant_address: "Händleradresse",
    merchant_phone: "Telefonnumer des Händlers",
    customer_name: "Kundennname",
    customer_number: "Kundennummer",
    customer_reference: "Kundenreferenz",
    customer_address: "Kundenadresse",
    customer_phone: "Telefonnumer des Kunden",
    customer_vat_number: "MwSt. Nummer des Kunden",
    customer_coc_number: "COC Kundennummer",
    customer_bank_account_number: "Kontonummer Kunde",
    customer_bank_account_number_bic: "BIC Kundenkonto",
    customer_website: "Kunden-Webseite",
    customer_email: "Kunden-Email",
    document_language: "Dokumentsprache",
    title: "Bezeichnung",
    payment_method: "Zahlungsart",
    with_breakfast: "Mit Frühstück?",
    can_book_again: "Kann man wieder buchen?",
    amount_ex_vat: "Betrag ohne MwSt.",
    vat_amount: "Betrag MwSt.",
    vat_percentage: "Prozent MwSt.",
    unit_of_measurement: "Messeinheit",
    vat_code: "MwSt. Code",
    amount_excl_vat: "Betrag ohne MwSt.",
    amount_incl_vat: "Betrag inkl. MwSt.",
    code: "Code"
};

export default fieldLabels;
