const fieldLabels = {
    document_type: "Document Type",
    amount: "Amount",
    amount_change: "Amount Change",
    amount_shipping: "Shipping Amount",
    vatamount: "VAT Amount",
    amountexvat: "Amount Ex. VAT",
    currency: "Currency",
    date: "Date",
    purchasedate: "Purchase Date",
    purchasetime: "Purchase Time",
    vatitems: "VAT Items",
    vat_context: "VAT Context",
    lines: "Line Items",
    paymentmethod: "Payment Method",
    payment_auth_code: "Payment Auth Code",
    payment_card_number: "Payment Card Number",
    payment_card_account_number: "Payment Card Account Number",
    payment_card_bank: "Payment Card Bank",
    payment_card_issuer: "Payment Card Issuer",
    payment_due_date: "Payment Due Date",
    terminal_number: "Terminal Number",
    document_subject: "Document Subject",
    package_number: "Package Number",
    invoice_number: "Invoice Number",
    invoice_type: "Invoice Type",
    receipt_number: "Receipt Number",
    shop_number: "Shop Number",
    transaction_number: "Transaction Number",
    transaction_reference: "Transaction Reference",
    order_number: "Order Number",
    table_number: "Table Number",
    table_group: "Table Group",
    server: "Server",
    merchant_name: "Merchant Name",
    merchant_id: "Merchant ID",
    merchant_coc_number: "Merchant CoC Number",
    merchant_vat_number: "Merchant VAT Number",
    merchant_bank_account_number: "Merchant Bank Account Number",
    merchant_bank_account_number_bic: "Merchant Bank Account Number BIC",
    merchant_chain_liability_bank_account_number: "Merchant Chain Liability Bank Account Number",
    merchant_chain_liability_amount: "Merchant Chain Liability Amount",
    merchant_bank_domestic_account_number: "Merchant Bank Domestic Account Number",
    merchant_bank_domestic_bank_code: "Merchant Bank Domestic Bank Code",
    merchant_website: "Merchant Website",
    merchant_email: "Merchant Email",
    merchant_address: "Merchant Address",
    merchant_street_name: "Merchant Street Name",
    merchant_house_number: "Merchant House Number",
    merchant_zipcode: "Merchant Zip Code",
    merchant_city: "Merchant City",
    merchant_municipality: "Merchant Municipality",
    merchant_province: "Merchant Province",
    merchant_country: "Merchant Country",
    merchant_country_code: "Merchant Country Code",
    merchant_phone: "Merchant Phone",
    merchant_main_activity_code: "Merchant Main Activity Code",
    customer_name: "Customer Name",
    customer_number: "Customer Number",
    customer_reference: "Customer Reference",
    customer_address: "Customer Address",
    customer_street_name: "Customer Street Name",
    customer_house_number: "Customer House Number",
    customer_zipcode: "Customer Zip Code",
    customer_city: "Customer City",
    customer_municipality: "Customer Municipality",
    customer_province: "Customer Province",
    customer_country: "Customer Country",
    customer_phone: "Customer Phone",
    customer_vat_number: "Customer VAT Number",
    customer_coc_number: "Customer CoC Number",
    customer_bank_account_number: "Customer Bank Account Number",
    customer_bank_account_number_bic: "Customer Bank Account Number BIC",
    customer_website: "Customer Website",
    customer_email: "Customer Email",
    payment_slip_code: "Payment Slip Code",
    payment_slip_reference_number: "Payment Slip Reference Number",
    payment_slip_customer_number: "Payment Slip Customer Number",
    document_language: "Document Language",
    matched_keywords: "Matched Keywords",
    matched_lineitems: "Matched Line Items",
    lineitems: "Line Items",
    matched_purchase_order_id: "Matched Purchase Order ID",
    barcodes: "Barcodes",
    hash: "Hash",
    hash_duplicate: "Hash Duplicate",
    raw_text: "Raw Text",
    name: "Name",
    project_number: "Project Number",
    customer: "Customer",
    city: "City",
    land: "Land",
    start_time: "Start Time",
    end_time: "End Time",
    break_time: "Break Time",
    description: "Description",
    has_customer_signature: "Has Customer Signature?",
    is_process_done: "Is Process Completed?",
    is_commissioned_work: "Is Commissioned Work?",
    is_without_measuring_technology: "Is Without Measuring Technology?",
    sign_date: "Signature Date",
    amount_excl_vat: "Amount Exclude VAT",
    amount_incl_vat: "Amount Include VAT",
    amount_incl_excl_vat_estimated: "Amount Including or Excluding VAT Estimated ?",
    percentage: "Percentage",
    code: "Code",
    amount_each: "Amount / Item",
    amount_ex_vat: "Amount Excluding VAT",
    vat_percentage: "VAT Percentage",
    vat_amount: "VAT Amount",
    quantity: "Quantity",
    unit_of_measurement: "Unit of Measurement",
    sku: "SKU",
    vat_code: "VAT Code",
    has_employee_signature: "Is Employee Signature?",
    is_in_egw: "Is In EGW?",
    fixed_lines: "Fixed Line Items",
    title: "Title",
    with_breakfast: "Is with Breakfast?",
    can_book_again: "Can Book Again?",
    payment_method: "Payment Method"
};

export default fieldLabels;
