
key_name_dict_path: config/key_name_dict.json

ocr:
  language_detector: facebook/metaclip-b32-400m
  language_thresh: 0.2
  target_language: en
  language_dict_path: config/language_dict.json
  device: Null
  resize_size: 640

llm_extract:
  invoice_template_path: config/invoice_template.txt

  openai:
    model: gpt-4o-mini
    temperature: 1.0
    max_tokens: 1024
  
  qwen2:
    model_name: Qwen/Qwen2-VL-2B-Instruct
    min_pixels: 200_704 # 256*28*28
    max_pixels: 1_003_520 # 1280*28*28
    max_new_tokens: 1024
    temperature: 0.7
    top_p: 0.8
    top_k: 20

postprocessing:
  model_name: llama3.1:8b
  request_timeout: 60

mongodb:
  uri: "mongodb://localhost:27017/"
  database: "invoice_db"
  collection: "invoices"

IES_host: localhost # Invoice Extraction System
IES_port: 8041