
ocr:
  language_detector: facebook/metaclip-b32-400m
  language_thresh: 0.2
  target_language: en
  language_dict_path: config/language_dict.json
  device: Null
  resize_size: 1080

llm_extract:

  openai:
    model_name: gpt-4o-mini
    temperature: 1.0
    max_tokens: 1024
  
  qwen2:
    model_name: Qwen/Qwen2-VL-2B-Instruct
    min_pixels: 200_704 # 256*28*28
    max_pixels: 1_003_520 # 1280*28*28
    max_new_tokens: 1024
    temperature: 0.7
    top_p: 0.8
    top_k: 20


postprocessing:
  model_name: llama3.1:8b
  request_timeout: 60

mongodb:
  # host: "mongodb::27017"
  # port: 27017
  # uri: mongodb://mongodb:27017/
  uri: "mongodb://localhost:27017/" 
  database: invoice_db
  collection: invoices

IES_host: '0.0.0.0' # Invoice Extraction System
IES_port: 8149

invoice_dict: #The template answer of invoice for LLM
  invoice 1: config/page_1_template.txt
  invoice 2: config/page_2_template.txt
  invoice 3: config/invoice_3_template.txt
  
invoice_txt_template:
  invoice 1: config/invoice_1_text_template.txt
  invoice 2: config/invoice_2_text_template.txt

invoice_txt_template_thresh: 0.3

timezone: Europe/Berlin
currencies_path: config/currencies.txt
frontend_fields_define_path: config/frontend_fields_define.json

country_and_city:
  file_path: config/travel_expenses-2024.xlsx
  sheet_name: Table 1 


excel:
  excel_file_path: config/user_template.xlsm
  sheet_name: April 24_0
  nachname_key: 'nachname'
  vorname_key: 'vorname'
  name_thresh: 20

ldap:
  ldap_server: ldap.forumsys.com
  ldap_port: 389
  base_dn: dc=example,dc=com

logging:  
  backupCount: 100 # delete log after 100 days
  logfile: logs/fvs.log
  when: midnight #rotate after a day
  libraries:
    PIL: WARNING
    pytesseract: WARNING
    pymongo: WARNING
    urllib3: WARNING
    requests: WARNING
    openai: WARNING
    httpx: WARNING
    uvicorn: WARNING
    httpcore: WARNING
    multipart: WARNING
