name: Multilanguage Invoice OCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12


    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install make
        make install

    # - name: run test base extractor and ollama setup
    #   run: |

    #     docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
    #     docker exec ollama ollama run llama3.1:8b
 
    #     python src/base_extractors.py

    - name: Run get employee names test
      run: python src/employee_name.py

    - name: Run excel_export test
      run: python src/export_excel/main.py

    - name: Run LDAP test
      run: python src/ldap_authen.py

    - name: Run validate invoice test
      run: python src/validate_invoice.py
    
    - name: Run email test
      run: python src/mail.py

    - name: Run paddleocr test
      run: python src/ocr_reader.py

    - name: Run invoice extraction test
      run: python src/invoice_extraction.py


    - name: run test MongoDB
      run: |

        docker run -d \
         --name mongodb \
         -p 27017:27017 \
         mongo:latest 

        # Run the mongodb 
        python src/mongo_database.py
